# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: eslite/jwt_revoker/jwt_revoke/v1/jwt_revoke.proto for package 'Eslite.JwtRevoker.JwtRevoke.V1'

require "grpc"
require "eslite/jwt_revoker/jwt_revoke/v1/jwt_revoke_pb"

module Eslite
  module JwtRevoker
    module JwtRevoke
      module V1
        module JWTRevokerService
          class Service
            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = "eslite.jwt_revoker.jwt_revoke.v1.JWTRevokerService"

            rpc :CheckRevoked, ::Eslite::JwtRevoker::JwtRevoke::V1::CheckRevokedRequest, ::Eslite::JwtRevoker::JwtRevoke::V1::CheckRevokedResponse
            rpc :RevokeToken, ::Eslite::JwtRevoker::JwtRevoke::V1::RevokeTokenRequest, ::Eslite::JwtRevoker::JwtRevoke::V1::RevokeTokenResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
