# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eslite/jwt_revoker/jwt_revoke/v1/jwt_revoke.proto

require "google/protobuf"

require "buf/validate/validate_pb"

descriptor_data = "\n1eslite/jwt_revoker/jwt_revoke/v1/jwt_revoke.proto\x12 eslite.jwt_revoker.jwt_revoke.v1\x1a\x1b\x62uf/validate/validate.proto\"4\n\x13\x43heckRevokedRequest\x12\x1d\n\x05token\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x05token\"B\n\x14\x43heckRevokedResponse\x12\x18\n\x07revoked\x18\x01 \x01(\x08R\x07revoked\x12\x10\n\x03jti\x18\x02 \x01(\tR\x03jti\"3\n\x12RevokeTokenRequest\x12\x1d\n\x05token\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x05token\"%\n\x13RevokeTokenResponse\x12\x0e\n\x02ok\x18\x01 \x01(\x08R\x02ok2\x8e\x02\n\x11JWTRevokerService\x12}\n\x0c\x43heckRevoked\x12\x35.eslite.jwt_revoker.jwt_revoke.v1.CheckRevokedRequest\x1a\x36.eslite.jwt_revoker.jwt_revoke.v1.CheckRevokedResponse\x12z\n\x0bRevokeToken\x12\x34.eslite.jwt_revoker.jwt_revoke.v1.RevokeTokenRequest\x1a\x35.eslite.jwt_revoker.jwt_revoke.v1.RevokeTokenResponseB\xb1\x02\n$com.eslite.jwt_revoker.jwt_revoke.v1B\x0eJwtRevokeProtoP\x01Z^eslite.com/eslitecorp/eslite-monorepo-backend/pb/eslite/jwt_revoker/jwt_revoke/v1;jwt_revokev1\xa2\x02\x03\x45JJ\xaa\x02\x1e\x45slite.JwtRevoker.JwtRevoke.V1\xca\x02\x1e\x45slite\\JwtRevoker\\JwtRevoke\\V1\xe2\x02*Eslite\\JwtRevoker\\JwtRevoke\\V1\\GPBMetadata\xea\x02!Eslite::JwtRevoker::JwtRevoke::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Eslite
  module JwtRevoker
    module JwtRevoke
      module V1
        CheckRevokedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eslite.jwt_revoker.jwt_revoke.v1.CheckRevokedRequest").msgclass
        CheckRevokedResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eslite.jwt_revoker.jwt_revoke.v1.CheckRevokedResponse").msgclass
        RevokeTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eslite.jwt_revoker.jwt_revoke.v1.RevokeTokenRequest").msgclass
        RevokeTokenResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("eslite.jwt_revoker.jwt_revoke.v1.RevokeTokenResponse").msgclass
      end
    end
  end
end
